import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { FaImage, FaMagic } from 'react-icons/fa';
import API from '../services/api';
import LoadingSpinner from '../components/Loadspinner'; // We'll reuse our spinner

export default function ImageGeneratorPage() {
  const [prompt, setPrompt] = useState('');
  const [imageUrl, setImageUrl] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  const handleGenerateImage = async () => {
    if (!prompt.trim()) {
      setError('Please enter a prompt to generate an image.');
      return;
    }
    setIsLoading(true);
    setError('');
    setImageUrl('');
    try {
      const res = await API.post('/ai/generate-image', { prompt });
      setImageUrl(res.data.image_url);
    } catch (err) {
      setError('Failed to generate image. The AI may have safety restrictions on this prompt.');
      console.error(err);
    }
    setIsLoading(false);
  };

  return (
    <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }}>
      <h1 className="text-4xl font-bold text-white mb-2">AI Picture Generator</h1>
      <p className="text-slate-400 text-lg mb-8">Describe any image you can imagine, and let the AI bring it to life.</p>
      
      <div className="flex flex-col lg:flex-row gap-8">
        {/* Left Column: Input and Controls */}
        <div className="lg:w-1/3 w-full bg-slate-800 p-6 rounded-xl border border-slate-700 h-fit">
          <h2 className="text-2xl font-bold text-white mb-4">Your Prompt</h2>
          <div className="relative">
            <textarea
              className="w-full h-40 p-4 bg-slate-900 rounded-lg text-slate-200 resize-none focus:outline-none focus:ring-2 focus:ring-purple-500"
              placeholder="e.g., A majestic lion wearing a crown, cinematic lighting, hyperrealistic..."
              value={prompt}
              onChange={(e) => setPrompt(e.target.value)}
            />
          </div>
          <button
            onClick={handleGenerateImage}
            disabled={isLoading}
            className="w-full mt-4 py-3 font-semibold text-white bg-purple-600 rounded-lg hover:bg-purple-700 disabled:bg-slate-700 disabled:cursor-not-allowed transition-all flex items-center justify-center gap-2"
          >
            <FaMagic />
            {isLoading ? 'Generating...' : 'Generate Image'}
          </button>
          {error && <p className="text-red-500 mt-4">{error}</p>}
        </div>

        {/* Right Column: Image Display */}
        <div className="lg:w-2/3 w-full aspect-square bg-slate-800 p-6 rounded-xl border-dashed border-2 border-slate-700 flex items-center justify-center">
          <AnimatePresence mode="wait">
            {isLoading ? (
              <motion.div key="loader" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}>
                <LoadingSpinner />
              </motion.div>
            ) : imageUrl ? (
              <motion.div key="image" initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }} className="w-full h-full">
                <img src={imageUrl} alt="Generated by AI" className="object-contain w-full h-full rounded-lg" />
              </motion.div>
            ) : (
              <motion.div key="placeholder" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center text-slate-500">
                <FaImage size={60} className="mx-auto mb-4" />
                <h3 className="text-xl font-semibold">Your generated image will appear here</h3>
                <p>Describe what you want to see in the prompt box.</p>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </motion.div>
  );
}